config/routes.rb
Rails.application.routes.draw do
  get "messages/new"
  get "messages/create"
  get "messages/index"
  get "messages/show"
  devise_for :users

  get "admin/index"

  namespace :admin do
    resources :t_shirts do
      member do
        delete :destroy
        patch :toggle_hidden
        get :toggle_hidden
        get :adjuct_stock
        patch :update_stock
      end
      resources :opinions, only: [:create, :destroy]
    end
    resources :messages, only: [:index, :show, :update]
  end
  
  root "t_shirts#index"

  resources :t_shirts do
    resources :opinions, only: [:create, :destroy, :update, :edit]
  end

  resources :cart_items, only: [:create, :update, :destroy]
  resource :cart, only: [:show, :destroy]
  resources :messages, only: [:new, :create, :index, :show]

  resources :carts do
    member do
      post :checkout
    end
  end

  resource :cart, only: [:show, :destroy, :update] do
    get 'pay'
    post 'process_payment'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "T Shirts" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <div class="header">
      <div class="header-content">
        <% if user_signed_in? %>
          <i>Hello, <%= current_user.name || current_user.email %>!</i>
          <div>
            <%= link_to "My Account", edit_user_registration_path %>
            <%= link_to "Contact with Us", messages_new_path %>
            <%= link_to "My Messages", messages_index_path %>
            <%= link_to cart_path do %>
              <% if session[:cart_id] %>
                <% cart = Cart.find_by(id: session[:cart_id]) %>
                <% if cart && cart.cart_items.any? %>
                  <%= cart.total_items %>
                <% else %>
                  <%= link_to "Cart", cart_path %>
                <% end %>
              <% else %>
                <%= link_to "Cart", cart_path %>
              <% end %>
            <% end %>

            <% if current_user.admin? %>
              <%= link_to "Admin Dashboard", admin_index_path %>
              <%= link_to "Message Center", admin_messages_path %>
            <% end %>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
          </div>
      <% else %>
        <%= button_to "Sign In", new_user_session_path, method: :get %>
        <%= button_to "Register", new_user_registration_path, method: :get %>
      <% end %>
      </div>
    </div>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <div class="home-button"><%= button_to "Home", root_path, method: :get %></div>

    <%= yield %>
  </body>
</html>